notifications:
  email:
    recipients:
      - admin@wlitsoft.com
  on_success: change
  on_failure: always

language: java

branches:
  only:
  - master

matrix:
  include:
  - os: linux
    env: CUSTOM_JDK="oraclejdk8"

test: off